name: vespa motoape frontend

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NODE_OPTIONS: --max_old_space_size=4096
  CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}
  ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
  DEV_ACM_CERTIFICATE_ARN: ${{ secrets.DEV_ACM_CERTIFICATE_ARN }}
  BUCKET_NAME: vespa-motoape-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Export env from aws ssm
        uses: nolmungshemung/chamber-action@main
        with:
          args: export --format dotenv --output-file .env motoape-frontend

      - name: Deploy to AWS
        run: yarn deploy
